spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: ERROR
    uk.gov.dwp.pairtest: DEBUG
    
ticket:
  prices: "{ADULT:25, CHILD:15, INFANT:0}"
