spring:
  application:
    name: ticket-service

  profiles:
    active: dev  # default profile, override with SPRING_PROFILES_ACTIVE

  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null

  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        json: application/json
        xml: application/xml

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"

swagger:
  enabled: true
  title: Ticket Booking API
  description: REST API for ticket booking system
  version: v1

rate-limiter:
  enabled: false   # placeholder - can be enabled later
  requests-per-second: 10

circuit-breaker:
  enabled: false   # placeholder - can be enabled later

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

ticket:
  prices:
    ADULT: 25
    CHILD: 15
    INFANT: 0

    