pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t cinema-tickets:1.0.0 .'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
