spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080/realms/demo}
          jwk-set-uri: ${OAUTH2_JWK_URI:http://localhost:8080/realms/demo/protocol/openid-connect/certs}
